backend:
  name: git-gateway
  branch: main
  media_folder: "public/assets/fotos"
  public_folder: "/assets/fotos"
  collections:
  - name: "produto"
    label: "Produto"
    folder: "src/produtos"
    create: true
    slug: "{{slug}}"
    fields: 
      - { lable: "Nome Produto", name: "nome", widget: "string" }
      - { lable: "Tags", name: "tags", widget: "list", default: ["prods"] }
      - { lable: "Descricao", name: "descricao", widget: "string" }
      - { lable: "Preço", name: "preco", widget: "number" }
      - { lable: "Foto", name: "fotoProd", widget: "image" }
      - { lable: "Body", name: "body", widget: "markdown" }

