backend:
  name: git-gateway
  branch: main


  media_folder: "public/assets/fotos"
  public_folder: "/assets/fotos"



  collections:
    - name: "blog"
      label: "Blog"
      folder: "/src/produtos"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields: 
        - { lable: "Nome Produto", name: "nome", widget: "string" }
        - { lable: "Tags", name: "tags", widget: "list", default: ["prods"] }
        - { lable: "Descricao", name: "descricao", widget: "string" }
        - { lable: "Preço", name: "preco", widget: "number" }
        - { lable: "Foto", name: "fotoProd", widget: "image" }
        

