backend:
  name: git-gateway
  repo: raphacomics/pet-teste
  branch: main

media_folder: "public/assets/fotos"
public_folder: "/assets/fotos"

collections:
  - name: "Variações"
    label: "Variações"
    folder: "src/produtos/variacoes"
    create: true
    slug: "{{variacaoTitle}}"
    fields:
      - { label: "Variação Titulo", name: "variacaoTitle", widget: "string" }
      - { label: "Variação", name: "variacaoTipo", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list", default: ["varia"] }

  - name: "produtos"
    label: "Produtos"
    folder: "src/produtos"
    create: true
    slug: "{{nome}}"
    fields:
      - { label: "Nome Produto", name: "nome", widget: "string" }
      - widget: "relation"
        collection: "Variações"
        name: "varia"
        label: "Escolha Variações"
        required: false
        multiple: true
        valueField: "variacaoTipo"
        searchFields: ["variacaoTitle"]
        displayFields: ["variacaoTitle", "variacaoTipo"]
      - { label: "Preço", name: "preco", widget: "number" }
      - { label: "Foto", name: "fotoProd", widget: "image" }
      - { label: "Variaçao Titulo", name: "opcaoNome", widget: "string" }
      - { label: "Variaçoes", name: "opcoes", widget: "list" }
      - { label: "Descricao", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["prods"] }
