backend:
  name: git-gateway
  repo: raphacomics/pet-teste
  branch: main

media_folder: "public/assets/fotos"
public_folder: "/assets/fotos"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "src/produtos"
    create: true
    slug: "{{nome}}"
    fields:
      - { lable: "Nome Produto", name: "nome", widget: "string" }
      - { lable: "Preço", name: "preco", widget: "number" }
      - { lable: "Foto", name: "fotoProd", widget: "image" }
      - { lable: "Opções", name: "opcoes", widget: "list" }
      - { label: "Descricao", name: "body", widget: "markdown" }
      - { lable: "Tags", name: "tags", widget: "list", default: ["prods"] }
