backend:
  name: git-gateway
  branch: main
  repo: raphacomics/pet-teste


media_folder: "public/assets/fotos"
public_folder: "/assets/fotos"



collections:
  - name: "produtos"
    label: "Produtos"
    folder: "src/produtos"
    create: true
<<<<<<< HEAD
    slug: "{{slug}}"
=======
    slug: "{{nome}}"
>>>>>>> 736c16fb95889adfa99441dc29a3104f7ac92e83
    fields: 
      - { lable: "Nome Produto", name: "nome", widget: "string" }
      - { lable: "Descricao", name: "descricao", widget: "string" }
      - { lable: "Preço", name: "preco", widget: "number" }
      - { lable: "Foto", name: "fotoProd", widget: "image" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { lable: "Tags", name: "tags", widget: "list", default: ["prods"] }
        

